Update crt-test-run.yml

diff --git a/.github/workflows/crt-test-run.yml b/.github/workflows/crt-test-run.yml
--- a/.github/workflows/crt-test-run.yml
+++ b/.github/workflows/crt-test-run.yml
@@ -28,5 +28,27 @@ jobs:
 
       # Runs a single command using the runners shell
       - name: Run a one-line script
-        run: echo Hello, world!
+        run: |
+          echo "Triggering CRT test execution..."
+
+          CRT_URL="${{ secrets.CRT_API_URL }}/projects/${{ vars.CRT_PROJECT_ID }}/jobs/${{ vars.CRT_TESTJOB_ID }}/builds"
+
+          response=$(curl -s -X POST "$CRT_URL" \
+            -H "X-Authorization: ${{ secrets.CRT_API_TOKEN }}" \
+            -H "Content-Type: application/json")
+
+            echo "CRT Trigger Response Message:"
+            MESSAGE=$(echo "$response" | jq -r '.message')
+            echo "$MESSAGE"
+
+            RUN_ID=$(echo "$MESSAGE" | grep -oE '[0-9]+')
+            if [ -z "$RUN_ID" ]; then
+            echo "Failed to extract Run ID from response message"
+            exit 1
+          fi
+
+          echo "Extracted CRT Run ID: $RUN_ID"
+          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
+
+            
 
